Add report for the RustDay MX 2017 event
rust-community/blog.community.rs pull request #12
Opened 2017-07-23 16:53 UTC by sebasmagri

2017-07-23 20:28 UTC, badboy requested changes
I noted some small things, but otherwise good to go!

2017-07-23 20:28 UTC, badboy commented on _posts/2017-07-23-rustdaymx-2017.md
> +On June 17th, the [Rust-MX](https://github.com/rustmx/team/) group teamed with [Mozilla México](http://www.mozilla-mexico.org/) to do its very first _whole day_ *Rust* event in Mexico City at the [Ne
`teamed up with`

2017-07-23 20:28 UTC, badboy commented on _posts/2017-07-23-rustdaymx-2017.md
> +After [5 meetups](https://meetup.com/rust-mx), the team decided it was a good moment to go a step further and plan a workshops day using the [RustBridge](https://bridge.community.rs/) curriculum as a
`After 5 previous meetups`

2017-07-23 20:28 UTC, badboy commented on _posts/2017-07-23-rustdaymx-2017.md
> +After [5 meetups](https://meetup.com/rust-mx), the team decided it was a good moment to go a step further and plan a workshops day using the [RustBridge](https://bridge.community.rs/) curriculum as a
`workshop day` (without the s on workshop)

2017-07-23 20:28 UTC, badboy commented on _posts/2017-07-23-rustdaymx-2017.md
> +Formed by members of the _Rust-MX_ group and with the help of the [Rust Community](https://community.rs) members _Brian Anderson_ and _Erick Tryzelaar_, the mentors team was in charge of preparing th
`and of` -> `and for`

2017-07-23 20:28 UTC, badboy commented on _posts/2017-07-23-rustdaymx-2017.md
> +Based on the results of the survey, we met again to review the [RustBridge materials](https://community.rs/rustbridge/) and see how could we adapt it to make them more attractive to the attendees, an
`how could we adapt` -> `how we could adapt`

2017-07-23 20:28 UTC, badboy commented on _posts/2017-07-23-rustdaymx-2017.md
> +Based on the results of the survey, we met again to review the [RustBridge materials](https://community.rs/rustbridge/) and see how could we adapt it to make them more attractive to the attendees, an
`scrap` -> `scrape`

2017-07-23 20:28 UTC, badboy commented on _posts/2017-07-23-rustdaymx-2017.md
> +The event day arrived and everyone was really anxious about it. We arrived the venue early to set up everything. People started coming and the _Installers_ team was there to help them. _Brian_ and _E
`arrived at the venue`

2017-07-23 20:28 UTC, badboy commented on _posts/2017-07-23-rustdaymx-2017.md
> +In the end, the team and the attendants were really satisfied. There were no CoC related issues and we got a peak of 52 participants that, plus volunteers and staff, did a total number of 72 persons.
`attendants` -> `attendees`

2017-07-23 20:28 UTC, badboy commented on _posts/2017-07-23-rustdaymx-2017.md
> +We hope this experience is useful for people in other places to do their own workshop days. Please, get in touch with [us](mailto:community-team@rust-lang.org) if you need support or feedback. We loo
Put `get in touch with us` into the mailto link (instead of just the single word). Much easier to hit then.

2017-07-24 06:14 UTC, sebasmagri commented
Thanks @badboy, I've updated the post with your corrections. Regards!

2017-07-24 19:36 UTC, badboy approved these changes

2017-07-24 20:12 UTC, sebasmagri commented
What would be needed to merge this? :-)

2017-07-24 20:23 UTC, badboy commented
Someone hitting the merge button!

2017-07-24 20:24 UTC, merged

2017-07-24 20:24 UTC, badboy commented
Which I just did

2017-07-24 20:25 UTC, badboy commented
Feel free to post to URLO, Reddit and tweet it mentioning @rustlang

2017-07-24 20:34 UTC, sebasmagri commented
Thanks @badboy!